language: node_js
node_js:
- '4'
- '5'
notifications:
  slack:
    on_success: change
    on_failure: always
    secure: KAdGnMBosGle9TTE7T/7ZveFHvKwYLf//uOIb16RLep3BSoyii49vzKCD/ea9u9UIFDTnKBu7YiE0e3CuiMHl2EGjCiL2paokO5MTHrvuG3RkM32G+H/7ZVqA9dyyZt2dxJY8bj2d6b4IbiByaaNPazJdVe8GWe9taJDWcMbUK2qVcfmvmkaiimO+9QeOeCQaRKFPF7WHgnHd5/yTq2gD4NUdNDbVhqCQfa370FyUMxCfkVQ0Bg3557jz0WCt7z173g98K5jjytmAkAkSx5C+bTFp+u1ozRDKKCsx5CpTe89lRl/0nUDNQ+FGrsdQyD62/7uOVZz4bffbt02H0hXE5YFpSqJc89biurzavOVV7N92TKzQ0ZnBBPBoON2Y9P141Q63L+w/UR0SGdHfPRFzii62hvTTyhYNJB2lKx3bXGEhYJpfKT7wBNXzEBoC/Kj/v9z69bggxgy+aG2XhZTxYCrWLUGyyouWrx619aPHh28JQdjrmzFYlwdN+GDrpjDxhXQoyDhQmjaSIq5weeprORVZxp3c/ctwllL7Wz6tPI6Yvf70g7y5v6V0/bTl8e2PVI5nXkWUXziGs1lFqauWIJbAdGbV+CqEzI+gdra4+13u1mO0I04BL5DIgAz5haS0h23vkDdZs2kAmcoTfQTl5AlsAVi135PRqK4kui6MzI=
